// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYKT8obqFb25BIJyhypi6aQNRxjHKOoaQ',
    appId: '1:188401743505:web:ccc6a40d65cc75f64e7130',
    messagingSenderId: '188401743505',
    projectId: 'noteapp-e8c4e',
    authDomain: 'noteapp-e8c4e.firebaseapp.com',
    storageBucket: 'noteapp-e8c4e.firebasestorage.app',
    measurementId: 'G-955JHC8J99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqcWZ7hoHoUf1rRmT639P4b5P7zt-4z2Q',
    appId: '1:188401743505:android:4e39e2f014eec9214e7130',
    messagingSenderId: '188401743505',
    projectId: 'noteapp-e8c4e',
    storageBucket: 'noteapp-e8c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdrr-0JpVuvbRvuif78Q5K-8-jUtvfaQ',
    appId: '1:188401743505:ios:c681fd0e5ecb40df4e7130',
    messagingSenderId: '188401743505',
    projectId: 'noteapp-e8c4e',
    storageBucket: 'noteapp-e8c4e.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdrr-0JpVuvbRvuif78Q5K-8-jUtvfaQ',
    appId: '1:188401743505:ios:c681fd0e5ecb40df4e7130',
    messagingSenderId: '188401743505',
    projectId: 'noteapp-e8c4e',
    storageBucket: 'noteapp-e8c4e.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYKT8obqFb25BIJyhypi6aQNRxjHKOoaQ',
    appId: '1:188401743505:web:2cd88fa687e589374e7130',
    messagingSenderId: '188401743505',
    projectId: 'noteapp-e8c4e',
    authDomain: 'noteapp-e8c4e.firebaseapp.com',
    storageBucket: 'noteapp-e8c4e.firebasestorage.app',
    measurementId: 'G-8LB8FVY7F2',
  );
}
